services:
  air:
    container_name: air
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /whoislive
    volumes:
      - ./:/whoislive
    ports:
      - 127.0.0.1:8000:8000
    networks:
      - whoislive
    depends_on:
      - redis

  redis:
    image: redis
    container_name: redis
    command: /usr/local/bin/redis-server /usr/local/redis/redis.conf
    deploy:
      resources:
        limits:
          memory: "100MB"
    volumes:
      - ./redis:/usr/local/redis/
    networks:
      whoislive:
        aliases:
          - redis
    expose:
      - 6379

networks:
  whoislive:
    driver: bridge